### PR TITLE
Add cross-building against Scala 2.12

### PR DESCRIPTION
**Pull request by richard-hunt**
In order to upgrade https://github.com/StreetContxt/lagom-kinesis to work with Lagom 1.4/Scala 2.12, support for cross-building against Scala 2.12 needs to be added to this library.

A couple of notes:

- The kpl-scala dependency is currently set to "LOCAL-SNAPSHOT" - this can be set appropriately once a 2.12 version of kpl-scala is published to bintray (I've raised a separate PR for that library).

- The Akka dependencies have been updated to 2.5.11 to match the versions used by Lagom 1.4.

### CODE REVIEW

**Comment by anikifoss** [comment]
In order to product 2.12 artifacts, we also need to update `.circleci/config.yml`.

We can fix the CI with another PR, but might as well do it in one shot. See [here](https://github.com/StreetContxt/kpl-scala/pull/8/files) for an example.

**Comment by richard-hunt** [comment]
I've updated the CircleCI configuration.  Also, if you publish a new version of kpl-scala to your bintray repo I can correct the "LOCAL-SNAPSHOT" dependency in the PR, or you can do this later at your convenience.

**Comment by anikifoss** [comment]
Thanks for patching the CI file!

`kpl-scala` is now cross-published as 1.0.4, so feel free to update the version when you can.

**Comment by richard-hunt** [comment]
No problem!  I've updated the dependency.  Once this library is published I'll update the dependencies in my lagom-kinesis PR as well.

**Comment by anikifoss** [comment]
Released as `2.0.1`, thanks for the patch!

**Pull request merged**
